### ISSUE TITLE
Feature request: Include notes with grades report

### ISSUE THREAD

**Issue by dianedouglas** [epicodus/epicenter#142]
It would literally save me hours if we could view the notes included with assessment reviews for each student in the grades report view. This would allow me to do quite a few things:

- When I have done a good job of explaining an error for one student, and then later another student makes the same mistake, I could go to the grades report and copy / paste the explanation.

- I could see at a glance what a student needs to work on and what I should check in with them about. For example, there's some people where I feel like I've explained to them why a detailed commit history is really important a couple times. So if I have an easy way of checking to see if I have already explained something fully or not, then I can either check on them in person during class or change the way I'm phrasing my explanation in the feedback to be a bit more direct: "As per last week's feedback, you still need to work on making more commits. If you need more information about that, come and talk to me." Instead of sounding like a broken record and reiterating an entire paragraph about how it's easier to track down bugs if everything isn't all squished into one commit.

**Comment by dustinbrownman** [comment]
So Diane, I think there are a couple of ways of displaying this information:

* The easiest would be to add the notes as another column on the side of the grades reports, but since the table is already a little...tough to read, I'm not sure this is the right approach.
* We could have a link on each row the table called "Notes" that will slide open or modal the notes to view. You wouldn't be seeing all the notes at once and it would require some JavaScript wizardry.
* We could just make a show page for a review and link to it from that grades report. Then you could see the quantitative (score) and qualitative (notes) feedback. The biggest limit to this is you could only see an individual report at a time, plus navigating back to the grades report is very slow (probably would have to make sure to open the review show page in a new tab).

What approach would work best for you? Or do you have any other ideas of how to display this information?

**Comment by dianedouglas** [comment]
I'm in favor of whatever is easiest because I'd love to have this feature be available soon. But you're right, I guess that adding another column could make it hard to read especially since some of the comments I leave are long and it might reformat the table in gross ways. I don't think it would be that hard to read if you gave the table cell a maximum height/width. 

But I think your third option is a good compromise between being clean and easy to implement - no need for js wizardry. I don't really need to see more than one set of comments at a time, just having them be available by name would be fine. A link in the table to a separate show page would be great because then I could have more than one open in a browser tab. But if either of the second two options are time consuming I'd gladly sacrifice some readability to have this feature.

**Comment by dianedouglas** [comment]
Also, I forked the repo and found the page with the table. I think I figured out how to add a column for the notes - I would just need you to show me how I would go about testing it. Or maybe I could get help from Jennifer or Maureen on the procedure? I don't want to make more work for you if you're busy, but this would be extremely handy.
